version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: stealth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stealth_garage
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: stealth_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=superowul-erwiii0-2-123
    depends_on:
      - db