spring.application.name=Stealth-Garage-API
# spring.profiles.active=test
spring.jpa.open-in-view=true

spring.datasource.url=jdbc:postgresql://localhost:5432/stealth_garage
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:superowul-erwiii0-2-123}